<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Package metadata">
    <Authors>Michal Zemek</Authors>
    <Product>DbsViewer</Product>
    <PackageProjectUrl>https://github.com/mzemek/DbsViewer</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mzemek/DbsViewer</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>ef-core;database;schema;er-diagram;documentation;blazor</PackageTags>
    <Version>0.1.0-alpha</Version>
  </PropertyGroup>

</Project>
