<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>DbsViewer.Dump</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DbsViewer.EfCore\DbsViewer.EfCore.csproj" />
    <ProjectReference Include="..\..\src\DbsViewer.SqlServer\DbsViewer.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\DbsViewer.Sqlite\DbsViewer.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\DbsViewer.Analysis\DbsViewer.Analysis.csproj" />
    <ProjectReference Include="..\..\samples\DbsViewer.SampleShop\DbsViewer.SampleShop.csproj" />
  </ItemGroup>

</Project>
