<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Pokrytí kódu">
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura,lcov,json</CoverletOutputFormat>
    <CoverletOutput>$(MSBuildThisFileDirectory)../../artifacts/coverage/tool/</CoverletOutput>
    <Include>[DbsViewer.Dump]*</Include>
    <SkipAutoProps>true</SkipAutoProps>
    <ExcludeByAttribute>GeneratedCodeAttribute,ExcludeFromCodeCoverageAttribute</ExcludeByAttribute>
    <Threshold>100,100,85</Threshold>
    <ThresholdType>line,method,branch</ThresholdType>
    <ThresholdStat>total</ThresholdStat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../tools/DbsViewer.Dump/DbsViewer.Dump.csproj" />
    <ProjectReference Include="../DbsViewer.TestKit/DbsViewer.TestKit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
