// <auto-generated />
using System;
using DbsViewer.SampleMigrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbsViewer.SampleMigrations.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DbsViewer.SampleMigrations.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("DbsViewer.SampleMigrations.Clanek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nadpis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Publikovano")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Clanky");
                });

            modelBuilder.Entity("DbsViewer.SampleMigrations.Komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanekId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClanekId");

                    b.ToTable("Komentare");
                });

            modelBuilder.Entity("DbsViewer.SampleMigrations.Clanek", b =>
                {
                    b.HasOne("DbsViewer.SampleMigrations.Autor", "Autor")
                        .WithMany("Clanky")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("DbsViewer.SampleMigrations.Komentar", b =>
                {
                    b.HasOne("DbsViewer.SampleMigrations.Clanek", "Clanek")
                        .WithMany()
                        .HasForeignKey("ClanekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clanek");
                });

            modelBuilder.Entity("DbsViewer.SampleMigrations.Autor", b =>
                {
                    b.Navigation("Clanky");
                });
#pragma warning restore 612, 618
        }
    }
}
